#!/bin/bash

echo "CROSS_COMPILE  : " ${CROSS_COMPILE}
echo "NOSTDINC_FLAGS : " ${NOSTDINC_FLAGS}
echo "KBUILD_CFLAGS  : " ${KBUILD_CFLAGS}
echo "LINUXINCLUDE   : " ${LINUXINCLUDE}

echo K_CROSSCOMPILE := ${CROSS_COMPILE} > ${OUTPUT}
echo K_NOSTDINC := ${NOSTDINC_FLAGS} >> ${OUTPUT}
echo K_CFLAGS := ${KBUILD_CFLAGS} >> ${OUTPUT}

OBJ_PATH=${objtree}

if [ $OBJ_PATH == "." ];
then
  OBJ_PATH=${PWD}
fi

OBJ_PATH=${OBJ_PATH}/

echo $@ ${LXINCLUDE} ${KBUILD_CFLAGS} | awk -v var="$OBJ_PATH" '
{
  x = 1
  while (x <= NF) {
    if ($x == "-include") {
      split($(x+1), chars, "")
      if (chars[1] != "/") {
        output_include = output_include " -include " var $(x+1)
      } else {
        output_include = output_include " -include " $(x+1)
      }
    }
    x++
  }
}
{
  y = 1
  while (y <= NF) {
    if ($y == "-I") {
      split($(y+1), chars, "")
      if (chars[1] != "/") {
        output_include = output_include " -I" var $(y+1)
      } else {
        output_include = output_include " -I" $(y+1)
      }
    } else if ($y ~ /-I/) {
      split($(y), chars, "")
      if (chars[3] != "/") {
        output_include = output_include " " substr($y, 1, 2) var substr($y, 3)
      } else {
        output_include = output_include " " $y
      }
    }
    y++
  }
}
BEGIN {
  output_include = ""
}
END {
  print "K_LXINCLUDE :=" output_include
}
' >> ${OUTPUT}

${_CC} $@
